language: csharp
mono: latest
solution: AccountingServer.sln

branches:
  - master

services:
  - docker
  - mongodb

install:
  - nuget restore AccountingServer.sln
  - nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Gen AccountingServer.sln
  - ./DeployParser.sh
  - msbuild /p:Configuration=Release AccountingServer.sln
  - mono ./testrunner/xunit.runners.2.4.0/tools/xunit.console.clr4.exe ./AccountingServer.Test/bin/Release/AccountingServer.Test.dll
  - docker build -t b1f6c1c4/accounting-frontend:latest ./nginx
  - docker build -t b1f6c1c4/accounting-backend:latest ./AccountingServer/bin/Release

after_success:
  - printf "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push b1f6c1c4/accounting-frontend accounting-backend
