version: 1.0.0.{build}

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

max_jobs: 1

image: Visual Studio 2022

clone_folder: c:\projects\accounting

shallow_clone: true
clone_depth: 1

environment:
  BUILD_DIR: /data/accounting-build
  COVERALLS_REPO_TOKEN:
    secure: lV5WGMiwfTLSBoDzNNzc3XpvvfjNO6oqjNDk6ccQugihg425h/NAvh6NVGHJgHjm

services:
  - mongodb

install:
  - dotnet tool install coveralls.net --tool-path tools
  - choco install --no-progress sed archiver nodejs
  - arc archive nginx/archive.tar.xz .
  - cd nginx && npm ci
  - nuget restore AccountingServer.sln

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version_prefix: 1.0.0.$(APPVEYOR_BUILD_NUMBER)
  package_version: 1.0.0
  assembly_version: 1.0.0.$(APPVEYOR_BUILD_NUMBER)
  file_version: $(APPVEYOR_BUILD_VERSION).$(APPVEYOR_BUILD_NUMBER)
  informational_version: $(APPVEYOR_REPO_COMMIT)

build_script:
  - cd nginx && npm run build
  - msbuild /p:Configuration=Gen     /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.QueryGeneration/AccountingServer.QueryGeneration.csproj
  - ps: ./scripts/DeployParser.ps1
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.Entities\AccountingServer.Entities.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.DAL\AccountingServer.DAL.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.BLL\AccountingServer.BLL.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.Shell\AccountingServer.Shell.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer\AccountingServer.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.Test\AccountingServer.Test.csproj

test_script:
  - dotnet test /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="xunit|System.Linq.Async|AltCover.Monitor|TestPlatform|testhost" /p:AltCoverFileFilter="Microsoft\.NET\.Test\.Sdk\.Program\.cs|QueryParser\.cs|SubtotalParser\.cs|QueryLexer\.cs|SubtotalLexer\.cs" & exit 0
  - .\tools\csmacnz.Coveralls --opencover -i AccountingServer.Test/coverage.xml --useRelativePaths & exit 0

artifacts:
  - path: 'nginx\dist'
    name: webpack
    type: Zip
  - path: 'AccountingServer.BLL\Parsing'
    name: Parsing
    type: Zip
  - path: 'AccountingServer\bin\Release\net9.0'
    name: AccountingServer
    type: Zip
