image:
  - Visual Studio 2017

environment:
  BUILD_DIR: /data/accounting-build
  SSH_HOST:
    secure: TE34vNZQ2n5JJ3N8F538PwzmBgJWiLzrYzLywtTdxFw=
  PRIVATE_KEY_PASSWORD:
    secure: duodF+XCTCjfkVZJtb2GQnVYS31itvrExBtEV5L4iNo=
  SSH_HOST_FINGERPRINT:
    secure: BgZQEU9cvGqvxXvOLd9gt2/JzDVkjLvm1lquCWTyGdms3nkYRO2D9BndIzNNVvQHjEX8FvuAgojdBsZ6bOuvtw1i8TfiCtN4eOg5q9rDsrtLSf2/04nIpXq5L5A2iJqUZ4MVbclJxtV4OJ4SrSz0NBzitGVxpNBZ7x/XNhbaqFPGidtLtWaUp89NGzGbf8X4ksv7GU3ELRocpq7VLE6XYvfdoq1Itx4JK23XzLBmEv0=

services:
  - mongodb

install:
  - ps: choco install --no-progress sed
  - nuget restore AccountingServer.sln
  - ps: curl -Uri https://raw.githubusercontent.com/rangercej/ssh-agent-powershell/master/ssh-agent.ps1 -OutFile ./ssh-agent.ps1
  - ps: . ./ssh-agent.ps1

before_build:
  - ps: Add-Content ~/.ssh/known_hosts "$env:SSH_HOST_FINGERPRINT"
  - ps: Start-SshAgent
  - ps: echo "$env:PRIVATE_KEY_PASSWORD" | ssh-add ./private_key.pem 2>&1; echo "Success"
  - ps: ssh "$env:SSH_HOST" docker version 2>&1; echo "Success"

build_script:
  - msbuild /p:Configuration=Gen AccountingServer.QueryGeneration/AccountingServer.QueryGeneration.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: ./DeployParser.ps1
  - msbuild /p:Configuration=Release AccountingServer.Entities\AccountingServer.Entities.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild /p:Configuration=Release AccountingServer.DAL\AccountingServer.DAL.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild /p:Configuration=Release AccountingServer.BLL\AccountingServer.BLL.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild /p:Configuration=Release AccountingServer.Shell\AccountingServer.Shell.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild /p:Configuration=Release AccountingServer\AccountingServer.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild /p:Configuration=Release AccountingServer.Test\AccountingServer.Test.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: ssh "$env:SSH_HOST" rm -rf "$env:BUILD_DIR"
  - ps: ssh "$env:SSH_HOST" mkdir -p "$env:BUILD_DIR"
  - ps: scp -r ./nginx ./AccountingServer/bin/Release "$($env:SSH_HOST):$($env:BUILD_DIR)" 2>&1; echo "Success"
  - ps: ssh "$env:SSH_HOST" docker build -t b1f6c1c4/accounting-frontend:latest "$($env:BUILD_DIR)/nginx" 2>&1; echo "Success"
  - ps: ssh "$env:SSH_HOST" docker build -t b1f6c1c4/accounting-backend:latest "$($env:BUILD_DIR)/Release" 2>&1; echo "Success"
  - ps: ssh "$env:SSH_HOST" rm -rf "$env:BUILD_DIR"

test_script:
  - xunit.console.clr4 .\AccountingServer.Test\bin\Release\AccountingServer.Test.dll /appveyor

deploy_script:
  - ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - ps: docker push b1f6c1c4/accounting-frontend accounting-backend
