version: 1.0.0.{build}

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

max_jobs: 1

image: Visual Studio 2022

clone_folder: c:\projects\accounting

shallow_clone: true
clone_depth: 1

environment:
  BUILD_DIR: /data/accounting-build
  PRIVATE_KEY_PASSWORD:
    secure: P4dfTh3tMeCUoNqkI6sL4lLPpYiC6Fnt3SOD/0Jq600=
  DOCKER_HOST:
    secure: 7Q8pmbTRGhC5XfAK+0tWopI12mMdS4ceKOGiebJZxws=
  DOCKER_CERT_PATH: c:\projects\accounting\certs
  DOCKER_TLS_VERIFY: YES
  DOCKER_MACHINE_NAME: accounting
  DOCKER_USER: b1f6c1c4
  DOCKER_PASS:
    secure: xh4rPu+6sbJUK4FlcoIUcrvOxrDhIhs2iLOtimcKtdd5aHi1M7hYXQtMg0JkluLe

services:
  - mongodb

install:
  - choco install --no-progress sed archiver nodejs
  - arc archive nginx/archive.tar.xz .
  - cd nginx && npm ci
  - nuget restore AccountingServer.sln
  - openssl rsa -in ./certs/key.pem -out ./certs/key.pem -passin env:PRIVATE_KEY_PASSWORD

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version_prefix: 1.0.0.$(APPVEYOR_BUILD_NUMBER)
  package_version: 1.0.0
  assembly_version: 1.0.0.$(APPVEYOR_BUILD_NUMBER)
  file_version: $(APPVEYOR_BUILD_VERSION).$(APPVEYOR_BUILD_NUMBER)
  informational_version: $(APPVEYOR_REPO_COMMIT)

build_script:
  - cd nginx && npm run build
  - msbuild /p:Configuration=Gen     /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.QueryGeneration/AccountingServer.QueryGeneration.csproj
  - ps: ./DeployParser.ps1
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.Entities\AccountingServer.Entities.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.DAL\AccountingServer.DAL.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.BLL\AccountingServer.BLL.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer.Shell\AccountingServer.Shell.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:VersionSuffix=$(APPVEYOR_BUILD_ID) AccountingServer\AccountingServer.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.Test\AccountingServer.Test.csproj

test_script:
  - dotnet test AccountingServer.Test\bin\Release\net6.0\AccountingServer.Test.dll

artifacts:
  - path: 'nginx\dist'
    name: webpack
    type: zip
  - path: 'AccountingServer.BLL\Parsing'
    name: Parsing
    type: zip
  - path: 'AccountingServer\bin\Release\net6.0'
    name: AccountingServer
    type: zip

before_deploy:
  - docker version

deploy_script:
  - docker build -t b1f6c1c4/accounting-frontend:latest ./nginx
  - docker build -t b1f6c1c4/accounting-backend:latest ./AccountingServer/bin/Release/net6.0
  - docker login -u %DOCKER_USER% -p %DOCKER_PASS%
  - docker push b1f6c1c4/accounting-frontend
  - docker push b1f6c1c4/accounting-backend
