version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

max_jobs: 1

image: Visual Studio 2019

clone_folder: c:\projects\accounting

shallow_clone: true
clone_depth: 1

environment:
  BUILD_DIR: /data/accounting-build
  PRIVATE_KEY_PASSWORD:
    secure: P4dfTh3tMeCUoNqkI6sL4lLPpYiC6Fnt3SOD/0Jq600=
  DOCKER_HOST:
    secure: 7Q8pmbTRGhC5XfAK+0tWopI12mMdS4ceKOGiebJZxws=
  DOCKER_CERT_PATH: c:\projects\accounting\certs
  DOCKER_TLS_VERIFY: YES
  DOCKER_MACHINE_NAME: accounting
  DOCKER_USER: b1f6c1c4
  DOCKER_PASS:
    secure: OoQDRsCepo+DniKf6E5WGQ==

services:
  - mongodb

install:
  - choco install --no-progress sed
  - nuget restore AccountingServer.sln
  - openssl rsa -in ./certs/key.pem -out ./certs/key.pem -passin env:PRIVATE_KEY_PASSWORD

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  - msbuild /p:Configuration=Gen     /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.QueryGeneration/AccountingServer.QueryGeneration.csproj
  - ps: ./DeployParser.ps1
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.Entities\AccountingServer.Entities.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.DAL\AccountingServer.DAL.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.BLL\AccountingServer.BLL.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.Shell\AccountingServer.Shell.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer\AccountingServer.csproj
  - msbuild /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" AccountingServer.Test\AccountingServer.Test.csproj

test:
  assemblies:
    only:
      - AccountingServer.Test\bin\Release\AccountingServer.Test.dll

artifacts:
  - path: 'AccountingServer.BLL\Parsing'
    name: Parsing
    type: zip
  - path: 'AccountingServer\bin\Release'
    name: AccountingServer
    type: zip

before_deploy:
  - docker version

deploy_script:
  - docker build -t b1f6c1c4/accounting-frontend:latest ./nginx
  - docker build -t b1f6c1c4/accounting-backend:latest ./AccountingServer/bin/Release
  - docker login -u %DOCKER_USER% -p %DOCKER_PASS%
  - docker push b1f6c1c4/accounting-frontend
  - docker push b1f6c1c4/accounting-backend
