version: "2.3"
services:

  nginx:
    image: b1f6c1c4/accounting-frontend
    ports:
      - "18080:443/tcp"
      - "18080:443/udp"
    volumes:
      - /data/accounting/certs:/opt/accounting/certs:ro
      - /data/accounting/nginx-cache:/var/cache/nginx
      - /data/accounting/nginx-pid:/var/run
    networks:
      - prod

  server:
    image: b1f6c1c4/accounting-backend
    read_only: true
    environment:
      MONGO_URI: /opt/accounting/atlas/url
      MONGO_CERT: /opt/accounting/atlas/cert.pem
    volumes:
      - /data/accounting/atlas:/opt/accounting/atlas:ro
      - /data/accounting/config.d:/opt/accounting/config.d:ro
    networks:
      - prod

networks:
  prod:
    driver: bridge
