services:

  nginx:
    image: b1f6c1c4/accounting-frontend
    restart: on-failure:3
    read_only: true
    volumes:
      - /data/accounting/certs:/opt/accounting/certs:ro
      - /data/accounting/nginx-cache:/var/cache/nginx
      - /data/accounting/nginx-pid:/var/run
      - /data/accounting/nginx-log:/var/log/nginx
    depends_on:
      - server
    extra_hosts:
      - "server:127.0.0.1"
    network_mode: host

  server:
    image: b1f6c1c4/accounting-backend
    restart: on-failure:3
    read_only: true
    environment:
      MONGO_URI: /opt/accounting/atlas/url
      MONGO_CERT: /opt/accounting/atlas/cert.pem
    volumes:
      - /data/accounting/atlas:/opt/accounting/atlas:ro
      - /data/accounting/config.d:/opt/accounting/config.d:ro
    ports:
      - "127.0.0.1:30000:30000"
    networks:
      - prod

networks:
  prod:
    driver: bridge
